$(document).ready ->
  navItems = $('.admin-menu li > a')
  navListItems = $('.admin-menu li')
  allWells = $('.admin-content')
  allWellsExceptFirst = $('.admin-content:not(:first)')
  allWellsExceptFirst.hide()
  navItems.click (e) ->
    e.preventDefault()
    navListItems.removeClass 'active'
    $(this).closest('li').addClass 'active'
    allWells.hide()
    target = $(this).attr('data-target-id')
    $('#' + target).show()
    return
  return

# ---
# generated by js2coffee 2.2.0
$ ->
  $('#date').datetimepicker()
  return